name: GitHub Pages

on:
  push:
    branches:
    - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 18

    - name: Install dependencies
      run: npm install

    - name: Run tests
      run: npm run test:headless

    - name: Build
      run: |
         npm run build:prod
         ./sonar-scanner ^
            -Dsonar.projectKey=Q2E-Angular ^
            -Dsonar.organization=Q2E-Angular ^
            -Dsonar.sources=Q2EV3_DEV\App\Q2E\Angular9\src ^
            -Dsonar.exclusions=Q2EV3_DEV\App\Q2E\Angular9\**\node_modules\**,Q2EV3_DEV\App\Q2E\Angular9\**/*.spec.ts ^
            -Dsonar.host.url="${{ secrets.SONAR_HOST_URL }}" ^
            -Dsonar.login="${{ secrets.SONAR_TOKEN_ANGULAR }}" ^
            -Dsonar.github.repository=$GITHUB_REPOSITORY ^
            -Dsonar.github.oauth=$GITHUB_TOKEN ^
            -Dsonar.analysis.mode=preview ^
            -Dsonar.verbose=true

    - name: Deploy
      if: success()
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: dist/angular-github-actions
        enable_jekyll: true
